# Generated by Django 5.0 on 2024-01-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('express', 'Express'), ('next_day', 'Next Day')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='get_digital_code_only',
            field=models.BooleanField(default=False),
        ),
    ]
