# Generated by Django 5.0 on 2024-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_game_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='carrier',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Action', 'ACTION'), ('Adventure', 'ADVENTURE'), ('Strategy', 'STRATEGY'), ('Role-Playing', 'RPG'), ('2D Platformer', 'PLATFORMER2D'), ('3D platformer', 'Platformer3D'), ('not assigned', 'TMP')], default='not assigned', max_length=40),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='images/'),
        ),
    ]
